In [10]:
import pandas as pd
import numpy as np

In [11]:
params = pd.read_csv('Params.csv')

In [15]:
disp = params.query('seq_len==336 and channels==100 and pred_len==336').sort_values(by="total_params", ascending=True)
disp[["model", "total_params", "gflops"]]

            model  total_params    gflops
88      SharedTST         14288  0.411184
106          Vera         33816  0.002970
34          FrNet        811332  0.173348
52   iTransformer       3501904  0.772859
70       PatchTST      22629923  0.211814
16        DLinear      33969600  0.045158

In [7]:
params.query("model == 'Vera'")[["seq_len", "pred_len", "channels", "total_params", "gflops"]]

     seq_len  pred_len  channels  total_params    gflops
90        96        96         1         12774  0.000014
91        96       336         1         23238  0.000022
92        96       720         1         42438  0.000034
93       336        96         1         22758  0.000022
94       336       336         1         33222  0.000030
95       336       720         1         52422  0.000042
96        96        96        10         12828  0.000143
97        96       336        10         23292  0.000220
98        96       720        10         42492  0.000343
99       336        96        10         22812  0.000220
100      336       336        10         33276  0.000297
101      336       720        10         52476  0.000420
102       96        96       100         13368  0.001434
103       96       336       100         23832  0.002202
104       96       720       100         43032  0.003430
105      336        96       100         23352  0.002202
106      336       336       100         33816  0.002970
107      336       720       100         53016  0.004198